// Generated by CoffeeScript 1.6.3
(function() {
  var OAuth2Client;

  OAuth2Client = (function() {
    function OAuth2Client(props) {
      if (props == null) {
        props = {};
      }
      this.id = props.id;
      this.name = props.name;
      this.type = props.type;
      this.profile = props.profile;
      this.authorizedGrantTypes = props.authorizedGrantTypes;
      this.setDefaults();
    }

    OAuth2Client.prototype.setDefaults = function() {
      return this.authorizedGrantTypes != null ? this.authorizedGrantTypes : this.authorizedGrantTypes = [];
    };

    OAuth2Client.prototype.isGrantTypeAuthorized = function(grantType) {
      return this.authorizedGrantTypes.indexOf(grantType) !== -1;
    };

    OAuth2Client.prototype.authorizeGrantType = function(grantType) {
      if (this.isGrantTypeAuthorized(grantType)) {
        return this;
      }
      this.authorizedGrantTypes.push(grantType);
      return this;
    };

    return OAuth2Client;

  })();

  module.exports = OAuth2Client;

}).call(this);

/*
//@ sourceMappingURL=Client.map
*/
