// Generated by CoffeeScript 1.6.3
(function() {
  var Service;

  Service = require('./Service');

  exports.createService = function(config) {
    return new Service(config);
  };

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
