// Generated by CoffeeScript 1.6.3
(function() {
  exports.ClientRepository = require('./ClientRepository');

  exports.Client = require('./Client');

  exports.Service = require('./Service');

  exports.createService = function(config) {
    return new exports.Service(config);
  };

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
