// Generated by CoffeeScript 1.6.3
(function() {
  var AbstractClientRepository;

  AbstractClientRepository = (function() {
    function AbstractClientRepository() {}

    AbstractClientRepository.prototype.find = function(id, callback) {
      throw Error("not implemented");
    };

    AbstractClientRepository.prototype.store = function(id, client, callback) {
      throw Error("not implemented");
    };

    return AbstractClientRepository;

  })();

  module.exports = AbstractClientRepository;

}).call(this);

/*
//@ sourceMappingURL=Abstract.map
*/
