// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    Abstract: require('./Abstract'),
    Memory: require('./Memory'),
    MongoJs: require('./MongoJs')
  };

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
