// Generated by CoffeeScript 1.6.3
(function() {
  var AbstractClientRepository, MemoryClientRepository,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  AbstractClientRepository = require('./Abstract');

  MemoryClientRepository = (function(_super) {
    __extends(MemoryClientRepository, _super);

    function MemoryClientRepository(props) {
      if (props == null) {
        props = {};
      }
      this.collection = props.collection;
      this.setDefaults();
    }

    MemoryClientRepository.prototype.setDefaults = function() {
      return this.collection != null ? this.collection : this.collection = {};
    };

    MemoryClientRepository.prototype.store = function(id, client, callback) {
      this.collection[id] = client;
      return callback(null, client);
    };

    MemoryClientRepository.prototype.find = function(id, callback) {
      var client;
      client = this.collection[id];
      return callback(null, client);
    };

    return MemoryClientRepository;

  })(AbstractClientRepository);

  module.exports = MemoryClientRepository;

}).call(this);

/*
//@ sourceMappingURL=Memory.map
*/
